### ISSUE TITLE
NewLine

### ISSUE THREAD

**Issue by rievertz** [RonnyWeiss/APEX-Copy-Text-2-Clipboard#1]
Hi Ronny,

Thanks for this little, but very helpful plugin!

My Question:  Is it possible to keep newline-Characters while copy? 
It looks like you are filtering out these characters.

Best regards
      Richard

**Comment by RonnyWeiss** [comment]
Hello Richard

Thank you for the issue. I fixed it in version 1.0.6.

Kind regards

Ronny
